/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jcat.aplication;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author pperezp
 */
public class JCat extends javax.swing.JFrame {
    private Jugador j1;
    private Jugador j2;
    private Jugador turno;
    private Ficha[] tablero;
    private int contJ1;
    private int contJ2;
    
    /**
     * Creates new form JCat
     */
    public JCat() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("JCat");
        contJ1 = 0;
        contJ2 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pos4 = new javax.swing.JLabel();
        pos3 = new javax.swing.JLabel();
        pos1 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        lblFicha = new javax.swing.JLabel();
        parte1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        parte2 = new javax.swing.JRadioButton();
        txtJugador2 = new javax.swing.JTextField();
        cboFicha = new javax.swing.JComboBox();
        lblTurno = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        lblTurno1 = new javax.swing.JLabel();
        lblJu1 = new javax.swing.JLabel();
        lblJu2 = new javax.swing.JLabel();
        lblc1 = new javax.swing.JLabel();
        lblc2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos4MouseReleased(evt);
            }
        });

        pos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos3MouseReleased(evt);
            }
        });

        pos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos1.setToolTipText("");
        pos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos1MouseReleased(evt);
            }
        });

        pos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos6MouseReleased(evt);
            }
        });

        pos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos2MouseReleased(evt);
            }
        });

        pos7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos7MouseReleased(evt);
            }
        });

        pos8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos8MouseReleased(evt);
            }
        });

        pos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos5MouseReleased(evt);
            }
        });

        pos9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pos7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pos9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFicha.setText("X");

        buttonGroup1.add(parte1);
        parte1.setSelected(true);
        parte1.setText("Parte jugando");

        jButton1.setText("Jugar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(parte2);
        parte2.setText("Parte jugando");

        txtJugador2.setText("Aru");

        cboFicha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "X" }));
        cboFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFichaActionPerformed(evt);
            }
        });

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno.setText("Juega:");

        txtJugador1.setText("Angeles");

        lblTurno1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno1.setForeground(new java.awt.Color(255, 0, 0));

        lblJu1.setText("Angeles");
        lblJu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblJu2.setText("Arú");
        lblJu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblc1.setText("0");
        lblc1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblc2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblc2.setText("0");
        lblc2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Enviar!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTurno1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJugador2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJugador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parte1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parte2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblJu1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(lblJu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parte1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parte2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTurno1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblc1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(lblJu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos4MouseReleased
        this.setFicha(4, pos4, turno.getFicha());
    }//GEN-LAST:event_pos4MouseReleased

    private void pos3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos3MouseReleased
        this.setFicha(3, pos3, turno.getFicha());
    }//GEN-LAST:event_pos3MouseReleased

    private void pos1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos1MouseReleased
        this.setFicha(1, pos1, turno.getFicha());

    }//GEN-LAST:event_pos1MouseReleased

    private void pos6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos6MouseReleased
        this.setFicha(6, pos6, turno.getFicha());
    }//GEN-LAST:event_pos6MouseReleased

    private void pos2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos2MouseReleased
        this.setFicha(2, pos2, turno.getFicha());
    }//GEN-LAST:event_pos2MouseReleased

    private void pos7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos7MouseReleased
        this.setFicha(7, pos7, turno.getFicha());
    }//GEN-LAST:event_pos7MouseReleased

    private void pos8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos8MouseReleased
        this.setFicha(8, pos8, turno.getFicha());
    }//GEN-LAST:event_pos8MouseReleased

    private void pos5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos5MouseReleased
        this.setFicha(5, pos5, turno.getFicha());
    }//GEN-LAST:event_pos5MouseReleased

    private void pos9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos9MouseReleased
        this.setFicha(9, pos9, turno.getFicha());
    }//GEN-LAST:event_pos9MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.reestablecerTablero();
        j1 = new Jugador(1, txtJugador1.getText(), (cboFicha.getSelectedIndex() == 0?Ficha.O:Ficha.X));
        j2 = new Jugador(2, txtJugador2.getText(), (cboFicha.getSelectedIndex() == 0?Ficha.X:Ficha.O));

        if(parte1.isSelected()){
            turno = j1;
        }else{
            turno = j2;
        }

        lblTurno1.setText(turno.getNombre());
        jButton1.setText("Jugar de nuevo");
        
        lblJu1.setText(j1.getNombre());
        lblJu2.setText(j2.getNombre());
        
        contJ1 = 0;
        contJ2 = 0;
        
        lblc1.setText("0");
        lblc2.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFichaActionPerformed
        if(cboFicha.getSelectedItem().toString().equalsIgnoreCase("O")){
            lblFicha.setText("X");
        }else{
            lblFicha.setText("O");
        }
    }//GEN-LAST:event_cboFichaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Thread h = new Thread(new Hilo());
        h.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboFicha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFicha;
    private javax.swing.JLabel lblJu1;
    private javax.swing.JLabel lblJu2;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblTurno1;
    private javax.swing.JLabel lblc1;
    private javax.swing.JLabel lblc2;
    private javax.swing.JRadioButton parte1;
    private javax.swing.JRadioButton parte2;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
    private void setFicha(int posicion, JLabel lbl, Ficha ficha){
        if(posicionLibre(posicion)){
            lbl.setIcon(new ImageIcon(getClass().getResource("/jcat/images/"+ficha.name()+".png")));
            tablero[posicion-1] = ficha;
            
            if(hayAlgunGanador()){
                if(turno.getId() == 1){
                    lblc1.setText(Integer.toString(++contJ1));
                }else{
                    lblc2.setText(Integer.toString(++contJ2));
                }
                
                if(JOptionPane.showConfirmDialog(this, "FELICIDADES "+turno.getNombre().toUpperCase()+"!, Desea jugar de nuevo?", "Preungta", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    this.reestablecerTablero();
                }
            }else if(ganoNadie()){
                if(JOptionPane.showConfirmDialog(this, "GANÓ NADIE!, Desea jugar de nuevo?", "Pregunta", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    this.reestablecerTablero();
                }
            }

            turno = (turno.getId() == 1 ? j2 : j1);
            lblTurno1.setText(turno.getNombre());
        }
        
        
        
    }

    private boolean hayAlgunGanador() {
        if((tablero[0] == tablero[1] && tablero[1] == tablero[2])
                &&
                (tablero[0] != null && tablero[1] != null && tablero[2] != null)){
            ponerGato(pos1, pos2, pos3);
            return true;
        }else if((tablero[3] == tablero[4] && tablero[4] == tablero[5])
                &&
                (tablero[3] != null && tablero[4] != null && tablero[5] != null)){
            ponerGato(pos4, pos5, pos6);
            return true;
        }else if((tablero[6] == tablero[7] && tablero[7] == tablero[8])
                &&
                (tablero[6] != null && tablero[7] != null && tablero[8] != null)){
            ponerGato(pos7, pos8, pos9);
            return true;
        }else if((tablero[0] == tablero[3] && tablero[3] == tablero[6])
                &&
                (tablero[0] != null && tablero[3] != null && tablero[6] != null)){
            ponerGato(pos1, pos4, pos7);
            return true;
        }else if((tablero[1] == tablero[4] && tablero[4] == tablero[7])
                &&
                (tablero[1] != null && tablero[4] != null && tablero[7] != null)){
            ponerGato(pos2, pos5, pos8);
            return true;
        }else if((tablero[2] == tablero[5] && tablero[5] == tablero[8])
                &&
                (tablero[2] != null && tablero[5] != null && tablero[8] != null)){
            ponerGato(pos3, pos6, pos9);
            return true;
        }else if((tablero[0] == tablero[4] && tablero[4] == tablero[8])
                &&
                (tablero[0] != null && tablero[4] != null && tablero[8] != null)){
            ponerGato(pos1, pos5, pos9);
            return true;
        }else if((tablero[2] == tablero[4] && tablero[4] == tablero[6])
                &&
                (tablero[2] != null && tablero[4] != null && tablero[6] != null)){
            ponerGato(pos3, pos5, pos7);
            return true;
        }
        return false;
    }

    private boolean ganoNadie() {
        int cont = 0;
        for(Ficha f : tablero){
            if(f != null){
                cont++;
            }
        }
        
        return cont == 9;
    }
    
    private void reestablecerTablero(){
//        for(int i=0; i<tablero.length; i++){
//            tablero[i] = null;
//        }
        tablero = new Ficha[9];
        pos1.setIcon(null);
        pos2.setIcon(null);
        pos3.setIcon(null);
        pos4.setIcon(null);
        pos5.setIcon(null);
        pos6.setIcon(null);
        pos7.setIcon(null);
        pos8.setIcon(null);
        pos9.setIcon(null);
        
    }

    private boolean posicionLibre(int posicion) {
        return tablero[posicion-1] == null;
    }

    private void ponerGato(JLabel l1, JLabel l2, JLabel l3) {
        l1.setIcon(new ImageIcon(getClass().getResource("/jcat/images/gato.png")));
        l2.setIcon(new ImageIcon(getClass().getResource("/jcat/images/gato.png")));
        l3.setIcon(new ImageIcon(getClass().getResource("/jcat/images/gato.png")));
    }
    
    private class Hilo implements Runnable{

        @Override
        public void run() {
            try {
                jButton2.setText("Enviando...");
                jButton2.setEnabled(false);
                jTextArea1.setEnabled(false);
                
                /*Establecer la Sesion de JavaMail */
                Properties props = new Properties();

                // Nombre del host de correo, es smtp.gmail.com
                props.setProperty("mail.smtp.host", "smtp.gmail.com");

                // TLS si está disponible
                props.setProperty("mail.smtp.starttls.enable", "true");

                // Puerto de gmail para envio de correos
                props.setProperty("mail.smtp.port","587");

                // Nombre del usuario
                props.setProperty("mail.smtp.user", "patodeath@gmail.com");

                // Si requiere o no usuario y password para conectarse.
                props.setProperty("mail.smtp.auth", "true");



                /*Construir un mensaje de texto sencillo */



                Session session = Session.getDefaultInstance(props);

                // Para obtener un log de salida más extenso
                session.setDebug(true);


                MimeMessage message = new MimeMessage(session);

                // Quien envia el correo
                message.setFrom(new InternetAddress("asd"));

                // A quien va dirigido
                message.addRecipient(Message.RecipientType.TO, new InternetAddress("patodeath@gmail.com"));

                message.setSubject("Feedback JCat");
                message.setText(jTextArea1.getText());

                Transport t = session.getTransport("smtp");

                // Aqui usuario y password de gmail
                t.connect("patodeath@gmail.com","PATR1cio$$");
                t.sendMessage(message,message.getAllRecipients());
                t.close();
                jButton2.setText("Enviar!");
                jButton2.setEnabled(true);
                jTextArea1.setText("");
                jTextArea1.setEnabled(true);
            } catch (MessagingException ex) {
                System.out.println("Exception: "+ex.getMessage());
            }
        }
    }
}
